.TH "Coocox project/main.c" 3 "Mon Apr 29 2019" "VGApi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coocox project/main.c
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'stm32_ub_vga_screen\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.ti -1c
.RI "void \fBsquaretest\fP ()"
.br
.RI "squaretest is een vroege functie om gevoel te krijgen voor de VGAput functies "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBwait\fP = 1"
.br
.ti -1c
.RI "int \fBi\fP =0"
.br
.ti -1c
.RI "int \fBj\fP =0"
.br
.ti -1c
.RI "int \fBk\fP =0"
.br
.ti -1c
.RI "int \fBl\fP =0"
.br
.ti -1c
.RI "int \fBstartpunt\fP [] = {10,200}"
.br
.ti -1c
.RI "int \fBeindpunt\fP [] = {100,100}"
.br
.ti -1c
.RI "int \fBbreedte\fP = 100"
.br
.ti -1c
.RI "int \fBkleur\fP = 255"
.br
.ti -1c
.RI "int \fBrichting\fP =0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG"

.SH "Function Documentation"
.PP 
.SS "int main (void)"

.SS "void squaretest ()"

.PP
squaretest is een vroege functie om gevoel te krijgen voor de VGAput functies Dit is de squaretest functie\&. Daniël Boon heeft deze gemaakt om te kijken hoe het er uit ziet als er een vierkant over het scherm beweegt\&. Kaya Hartwig heeft deze proberen te verbeteren door het scherm op het juiste moment te laten verversen, dit is tot op heden nog niet gelukt\&. pinnetje hier 
.SH "Variable Documentation"
.PP 
.SS "int breedte = 100"

.SS "int eindpunt[] = {100,100}"

.SS "int i =0"

.SS "int j =0"

.SS "int k =0"

.SS "int kleur = 255"

.SS "int l =0"

.SS "int richting =0"

.SS "int startpunt[] = {10,200}"

.SS "int wait = 1"

.SH "Author"
.PP 
Generated automatically by Doxygen for VGApi from the source code\&.
